---
language: generic

sudo: required

services:
  - docker

install:
  - docker build -t thymeflow/front .

script:
  - docker run thymeflow/front ember test

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
